# Generated by Django 4.2.27 on 2026-01-01 15:35

import assets.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('mutual_funds', 'Mutual Funds'), ('stocks', 'Stocks'), ('lands', 'Lands'), ('flats', 'Flats'), ('fixed_deposit', 'Fixed Deposit'), ('medical_insurance', 'Medical Insurance'), ('life_insurance', 'Life Insurance'), ('gold', 'Gold')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Current value of the asset', max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(help_text='Purchase/Start date')),
                ('end_date', models.DateField(blank=True, help_text='Maturity/End date (if applicable)', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude for land assets', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude for land assets', max_digits=10, null=True)),
                ('policy_number', models.CharField(blank=True, help_text='Policy/Account number for insurance, FD, etc.', max_length=100, null=True)),
                ('institution', models.CharField(blank=True, help_text='Bank, Insurance company, Broker, etc.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assets.models.asset_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('name', models.CharField(blank=True, help_text='Document name/description', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Document',
                'verbose_name_plural': 'Asset Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('upload', 'Document Uploaded'), ('download', 'Document Downloaded')], max_length=20)),
                ('asset_name', models.CharField(help_text='Asset name at time of action', max_length=255)),
                ('asset_category', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
