# Generated by Django 4.2.27 on 2026-01-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='asset',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area measurement for land/flat', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('sqft', 'Square Feet'), ('sqm', 'Square Meters'), ('acres', 'Acres'), ('hectares', 'Hectares'), ('cents', 'Cents'), ('guntha', 'Guntha')], help_text='Unit of area measurement', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_nav',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Current NAV/price per unit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='folio_number',
            field=models.CharField(blank=True, help_text='Folio number for mutual funds', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='gold_purity',
            field=models.CharField(blank=True, choices=[('24k', '24 Karat (99.9%)'), ('22k', '22 Karat (91.6%)'), ('18k', '18 Karat (75%)'), ('14k', '14 Karat (58.3%)')], help_text='Gold purity/karat', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate (%) for FD', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maturity_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maturity amount for FD', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='nominee',
            field=models.CharField(blank=True, help_text='Nominee name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Premium amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='premium_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], help_text='Premium payment frequency', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Purchase price per unit/share', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sum_assured',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum assured for insurance', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Number of units/shares', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in grams for gold', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='file_data',
            field=models.BinaryField(blank=True, help_text='Binary file content stored in database', null=True),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='file_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True),
        ),
    ]
